
package com.mycompany.crud.soap.client.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Eclipse Metro/3.0.2 (RELEASE-3.0.2-4d220c5; 2021-08-02T05:18:16+0000) JAXWS-RI/3.0.2 JAXWS-API/3.0.1 JAXB-RI/3.0.2 JAXB-API/3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "MarcaVehicleService", targetNamespace = "http://ws.soap.crud.mycompany.com/", wsdlLocation = "http://localhost:8080/CRUD-SOAP/MarcaVehicleService?WSDL")
public class MarcaVehicleService
    extends Service
{

    private final static URL MARCAVEHICLESERVICE_WSDL_LOCATION;
    private final static WebServiceException MARCAVEHICLESERVICE_EXCEPTION;
    private final static QName MARCAVEHICLESERVICE_QNAME = new QName("http://ws.soap.crud.mycompany.com/", "MarcaVehicleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CRUD-SOAP/MarcaVehicleService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MARCAVEHICLESERVICE_WSDL_LOCATION = url;
        MARCAVEHICLESERVICE_EXCEPTION = e;
    }

    public MarcaVehicleService() {
        super(__getWsdlLocation(), MARCAVEHICLESERVICE_QNAME);
    }

    public MarcaVehicleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MARCAVEHICLESERVICE_QNAME, features);
    }

    public MarcaVehicleService(URL wsdlLocation) {
        super(wsdlLocation, MARCAVEHICLESERVICE_QNAME);
    }

    public MarcaVehicleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MARCAVEHICLESERVICE_QNAME, features);
    }

    public MarcaVehicleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MarcaVehicleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MarcaVehicleWebService
     */
    @WebEndpoint(name = "MarcaVehicleWebServicePort")
    public MarcaVehicleWebService getMarcaVehicleWebServicePort() {
        return super.getPort(new QName("http://ws.soap.crud.mycompany.com/", "MarcaVehicleWebServicePort"), MarcaVehicleWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MarcaVehicleWebService
     */
    @WebEndpoint(name = "MarcaVehicleWebServicePort")
    public MarcaVehicleWebService getMarcaVehicleWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.soap.crud.mycompany.com/", "MarcaVehicleWebServicePort"), MarcaVehicleWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MARCAVEHICLESERVICE_EXCEPTION!= null) {
            throw MARCAVEHICLESERVICE_EXCEPTION;
        }
        return MARCAVEHICLESERVICE_WSDL_LOCATION;
    }

}
