
package com.mycompany.crud.soap.client.stubs;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Eclipse Metro/3.0.2 (RELEASE-3.0.2-4d220c5; 2021-08-02T05:18:16+0000) JAXWS-RI/3.0.2 JAXWS-API/3.0.1 JAXB-RI/3.0.2 JAXB-API/3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "MarcaVehicleWebService", targetNamespace = "http://ws.soap.crud.mycompany.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MarcaVehicleWebService {


    /**
     * 
     * @param brandName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearMarca", targetNamespace = "http://ws.soap.crud.mycompany.com/", className = "com.mycompany.crud.soap.client.stubs.CrearMarca")
    @ResponseWrapper(localName = "crearMarcaResponse", targetNamespace = "http://ws.soap.crud.mycompany.com/", className = "com.mycompany.crud.soap.client.stubs.CrearMarcaResponse")
    @Action(input = "http://ws.soap.crud.mycompany.com/MarcaVehicleWebService/crearMarcaRequest", output = "http://ws.soap.crud.mycompany.com/MarcaVehicleWebService/crearMarcaResponse")
    public String crearMarca(
        @WebParam(name = "brandName", targetNamespace = "")
        String brandName);

    /**
     * 
     * @return
     *     returns java.util.List<com.mycompany.crud.soap.client.stubs.MarcaVehicle>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "llistarMarques", targetNamespace = "http://ws.soap.crud.mycompany.com/", className = "com.mycompany.crud.soap.client.stubs.LlistarMarques")
    @ResponseWrapper(localName = "llistarMarquesResponse", targetNamespace = "http://ws.soap.crud.mycompany.com/", className = "com.mycompany.crud.soap.client.stubs.LlistarMarquesResponse")
    @Action(input = "http://ws.soap.crud.mycompany.com/MarcaVehicleWebService/llistarMarquesRequest", output = "http://ws.soap.crud.mycompany.com/MarcaVehicleWebService/llistarMarquesResponse")
    public List<MarcaVehicle> llistarMarques();

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "eliminarMarca", targetNamespace = "http://ws.soap.crud.mycompany.com/", className = "com.mycompany.crud.soap.client.stubs.EliminarMarca")
    @ResponseWrapper(localName = "eliminarMarcaResponse", targetNamespace = "http://ws.soap.crud.mycompany.com/", className = "com.mycompany.crud.soap.client.stubs.EliminarMarcaResponse")
    @Action(input = "http://ws.soap.crud.mycompany.com/MarcaVehicleWebService/eliminarMarcaRequest", output = "http://ws.soap.crud.mycompany.com/MarcaVehicleWebService/eliminarMarcaResponse")
    public String eliminarMarca(
        @WebParam(name = "id", targetNamespace = "")
        Integer id);

}
